### PR TITLE
separate public and private methods

### PR DESCRIPTION
**Pull request by vchaptsev**
Hi!
So I've been using a fork of your plugin for a while.
I'm ok with it, but I guess you may like some of the changes.

The main idea is to separate public and private stuff & validate all the magic methods.

P.S. Thank you again for the plugin, I really like it 👍

### CODE REVIEW

**Comment by Melevir** [comment]
Hi. Thanks fo pr, I really like it, but it requires some additional work.
Now Django-related fields checks are removed and it's not good. Please, return the logic.

**Comment by vchaptsev** [comment]
Fair enough, maybe like that?

**Comment by vchaptsev** [comment]
@Melevir it's not like I'm in a hurry, just curious 😄

**Comment by Melevir** [comment]
Sorry for taking it so long and thanks a lot for your work.

**Comment by Melevir** [comment]
After some additional testing I found out that new order is not backward compatible: codebase, that produced no errors, now produce lots of errors. That's not good.
So I changed ordering of methods to minimize amount of backward incompatible  changes.

Next step is to make the order configurable, you can get status in https://github.com/best-doctor/flake8-class-attributes-order/issues/8

Thanks again for the pr: new node types are very handy.

**Pull request merged**
